### ISSUE TITLE
Change Meta and OG Description 

### ISSUE THREAD

**Issue by ridvanbaluyos** [ridvanbaluyos/earthquake#6]
In the earthquake details page, change the meta and open graph description to be the same as the title.

**Comment by MrClan** [comment]
I'll try to do this.

**Comment by MrClan** [comment]
I've submitted a pull request. Please have a look.

**Comment by ridvanbaluyos** [comment]
![screen shot 2017-10-24 at 13 57 29](https://user-images.githubusercontent.com/156903/31926783-52a27cf6-b8c3-11e7-90f5-e121043884d5.png)


Verified on production. Thanks @MrClan
